name: Django CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'car_dealership_project/dealerships/**'
      - '.github/workflows/**'
      - 'README.md'
      - 'manage.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: car_dealership_project/dealerships
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Django Checks
        run: python manage.py check

      - name: Run Migrations (Optional)
        run: python manage.py migrate

      - name: Collect Static Files
        run: python manage.py collectstatic --noinput

      # Optional: Trigger deploy to Render via webhook or CLI here
      - name: Placeholder Deploy
        run: echo "You can add your Render deploy command here"
